name: Daily Cron Job

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-hello-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run hello script
      run: bash hello.sh
